from django.urls import path

from .template_views import (
    DepartmentDetailTemplateView,
    DepartmentListCreateTemplateView,
    EmployeeDetailTemplateView,
    EmployeeListCreateTemplateView,
    EmployeeStatsTemplateView,
    SectionDetailTemplateView,
    SectionListCreateTemplateView,
    UserAccessListTemplateView,
    UserDetailTemplateView,
    UserListCreateTemplateView,
)
from .views import (
    BnpzIdExchangeApiView,
    EmployeeBaseImageChangeLogDetailApiView,
    EmployeeBaseImageUpdateApiView,
    EmployeeBaseImageChangeLogListApiView,
    DepartmentDetailApiView,
    DepartmentListApiView,
    EmployeeDetailApiView,
    EmployeeFaceIdExemptionApiView,
    EmployeeFaceVerifyApiView,
    EmployeeListCreateApiView,
    EmployeeUpsertApiView,
    FaceDetectBoxesApiView,
    LivenessHeadPoseApiView,
    ProfileFaceVerifyApiView,
    SectionDetailApiView,
    SectionListApiView,
    UserLoginFaceVerifyApiView,
)


urlpatterns = [
    path('departments/', DepartmentListApiView.as_view()),
    path('departments/<int:pk>/', DepartmentDetailApiView.as_view()),
    path('sections/', SectionListApiView.as_view()),
    path('sections/<int:pk>/', SectionDetailApiView.as_view()),
    path('employees/', EmployeeListCreateApiView.as_view()),
    path('employees/upsert/', EmployeeUpsertApiView.as_view()),
    path('employees/face-id-exemptions/', EmployeeFaceIdExemptionApiView.as_view()),
    path('employees/base-image-change-logs/', EmployeeBaseImageChangeLogListApiView.as_view()),
    path('employees/base-image-change-logs/<int:pk>/', EmployeeBaseImageChangeLogDetailApiView.as_view()),
    path('employees/<slug:slug>/face-id-exemption/', EmployeeFaceIdExemptionApiView.as_view()),
    path('employees/<slug:slug>/', EmployeeDetailApiView.as_view()),
    path('employees/<slug:slug>/base-image/', EmployeeBaseImageUpdateApiView.as_view()),
    path('employees/<slug:slug>/face-verify/', EmployeeFaceVerifyApiView.as_view()),
    path('face/detect-boxes/', FaceDetectBoxesApiView.as_view()),
    path('liveness/head-pose/', LivenessHeadPoseApiView.as_view()),
    path('auth/profile-face-verify/', ProfileFaceVerifyApiView.as_view()),
    path('auth/login-face-verify/', UserLoginFaceVerifyApiView.as_view()),
    path('auth/bnpzid/exchange/', BnpzIdExchangeApiView.as_view()),
    path('template/departments/', DepartmentListCreateTemplateView.as_view()),
    path('template/departments/<int:pk>/', DepartmentDetailTemplateView.as_view()),
    path('template/sections/', SectionListCreateTemplateView.as_view()),
    path('template/sections/<int:pk>/', SectionDetailTemplateView.as_view()),
    path('template/employees/', EmployeeListCreateTemplateView.as_view()),
    path('template/employees/<int:pk>/', EmployeeDetailTemplateView.as_view()),
    path('template/employees/stats/', EmployeeStatsTemplateView.as_view()),
    path('template/users/', UserListCreateTemplateView.as_view()),
    path('template/user-access/', UserAccessListTemplateView.as_view()),
    path('template/users/<int:pk>/', UserDetailTemplateView.as_view()),
]