from django.urls import path

from .views import (
    DepartmentDetailApiView,
    DepartmentListApiView,
    EmployeeDetailApiView,
    EmployeeBaseImageUpdateApiView,
    EmployeeFaceIdExemptionApiView,
    EmployeeFaceVerifyApiView,
    EmployeeListCreateApiView,
    EmployeeUpsertApiView,
    FaceDetectBoxesApiView,
    SectionDetailApiView,
    SectionListApiView,
    UserLoginFaceVerifyApiView,
)
from .template_views import (
    DepartmentListCreateTemplateView,
    DepartmentDetailTemplateView,
    SectionListCreateTemplateView,
    SectionDetailTemplateView,
    EmployeeImportExcelTemplateView,
    EmployeeListCreateTemplateView,
    EmployeeDetailTemplateView,
    EmployeeStatsTemplateView,
    UserListCreateTemplateView,
    UserAccessListTemplateView,
    UserDetailTemplateView,
)
from .web_views import (
    DashboardView,
    DepartmentsWebView,
    EmployeeCreateWebView,
    EmployeeDeleteWebView,
    EmployeeDetailWebView,
    EmployeeEditWebView,
    LoginPageView,
    LogoutPageView,
    ProfileEditWebView,
    SectionsWebView,
    UserAccessWebView,
    UsersWebView,
)


urlpatterns = [
    # Web Interface Routes
    path('login/', LoginPageView.as_view(), name='login'),
    path('bnpzid/authorize/', LoginPageView.as_view(), name='bnpzid-authorize'),
    path('logout/', LogoutPageView.as_view(), name='logout'),
    path('', DashboardView.as_view(), name='dashboard'),
    path('employees/', DashboardView.as_view(), name='employees-web'),
    path('departments/', DepartmentsWebView.as_view(), name='departments-web'),
    path('sections/', SectionsWebView.as_view(), name='sections-web'),
    path('employees/create/', EmployeeCreateWebView.as_view(), name='employee-create-web'),
    path('employees/<slug:slug>/', EmployeeDetailWebView.as_view(), name='employee-detail-web'),
    path('employees/<slug:slug>/edit/', EmployeeEditWebView.as_view(), name='employee-edit-web'),
    path('employees/<slug:slug>/delete/', EmployeeDeleteWebView.as_view(), name='employee-delete-web'),
    path('profile/edit/', ProfileEditWebView.as_view(), name='profile-edit-web'),
    path('settings/users/', UsersWebView.as_view(), name='users-web'),
    path('settings/access/', UserAccessWebView.as_view(), name='user-access-web'),
    
    # Original API endpoints
    path('api/departments/', DepartmentListApiView.as_view()),
    path('api/departments/<int:pk>/', DepartmentDetailApiView.as_view()),
    path('api/sections/', SectionListApiView.as_view()),
    path('api/sections/<int:pk>/', SectionDetailApiView.as_view()),
    path('api/employees/', EmployeeListCreateApiView.as_view()),
    path('api/employees/upsert/', EmployeeUpsertApiView.as_view()),
    path('api/employees/face-id-exemptions/', EmployeeFaceIdExemptionApiView.as_view()),
    path('api/employees/<slug:slug>/face-id-exemption/', EmployeeFaceIdExemptionApiView.as_view()),
    path('api/employees/<slug:slug>/', EmployeeDetailApiView.as_view()),
    path('api/employees/<slug:slug>/base-image/', EmployeeBaseImageUpdateApiView.as_view()),
    path('api/employees/<slug:slug>/face-verify/', EmployeeFaceVerifyApiView.as_view()),
    path('api/face/detect-boxes/', FaceDetectBoxesApiView.as_view()),
    path('api/auth/login-face-verify/', UserLoginFaceVerifyApiView.as_view()),
    
    # Template CRUD endpoints
    path('api/template/departments/', DepartmentListCreateTemplateView.as_view()),
    path('api/template/departments/<int:pk>/', DepartmentDetailTemplateView.as_view()),
    path('api/template/sections/', SectionListCreateTemplateView.as_view()),
    path('api/template/sections/<int:pk>/', SectionDetailTemplateView.as_view()),
    path('api/template/employees/', EmployeeListCreateTemplateView.as_view()),
    path('api/template/employees/import-excel/', EmployeeImportExcelTemplateView.as_view()),
    path('api/template/employees/<int:pk>/', EmployeeDetailTemplateView.as_view()),
    path('api/template/employees/stats/', EmployeeStatsTemplateView.as_view()),
    path('api/template/users/', UserListCreateTemplateView.as_view()),
    path('api/template/user-access/', UserAccessListTemplateView.as_view()),
    path('api/template/users/<int:pk>/', UserDetailTemplateView.as_view()),
]