# Generated by Django 4.2 on 2026-03-24 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('boss_full_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='employees.department')),
            ],
            options={
                'ordering': ['department__name', 'name'],
                'unique_together': {('department', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(default='default', max_length=100)),
                ('external_id', models.CharField(blank=True, default='', max_length=100)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('surname', models.CharField(blank=True, default='', max_length=255)),
                ('tabel_number', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=8)),
                ('height', models.CharField(blank=True, default='', max_length=255)),
                ('clothe_size', models.CharField(blank=True, default='', max_length=255)),
                ('shoe_size', models.CharField(blank=True, default='', max_length=255)),
                ('headdress_size', models.CharField(blank=True, default='', max_length=255)),
                ('base_image', models.ImageField(blank=True, null=True, upload_to='employee_base_images/')),
                ('position', models.TextField(blank=True, default='')),
                ('date_of_employment', models.DateField(blank=True, null=True)),
                ('date_of_change_position', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('requires_face_id_checkout', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.section')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'surname', 'tabel_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source_system', 'external_id'), name='employees_employee_source_external_unique'),
        ),
    ]
