# Generated by Django 4.2 on 2026-03-26 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number_1',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон 1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number_2',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон 2'),
        ),
        migrations.AlterField(
            model_name='department',
            name='boss_full_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Руководитель цеха'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название цеха'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_base_images/', verbose_name='Базовое изображение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_change_position',
            field=models.DateField(blank=True, null=True, verbose_name='Дата изменения должности'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department', verbose_name='Цех'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=8, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Метаданные'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.TextField(blank=True, default='', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='requires_face_id_checkout',
            field=models.BooleanField(default=True, verbose_name='Требует проверку по лицу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.section', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='source_system',
            field=models.CharField(default='default', max_length=100, verbose_name='Источник системы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tabel_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='section',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='employees.department', verbose_name='Цех'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название отдела'),
        ),
    ]
