# Generated by Django 4.2 on 2026-03-27 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_face_images/', verbose_name='Эталонное изображение лица'),
        ),
    ]
