# Generated by Django 6.0.3 on 2026-04-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_userprofile_eimzo_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jshshir',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='ЖШШИР'),
        ),
        migrations.AddField(
            model_name='employee',
            name='login',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Логин'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, default='', max_length=7, verbose_name='Номер паспорта'),
        ),
        migrations.AddField(
            model_name='employee',
            name='passport_series',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Серия паспорта'),
        ),
        migrations.AddField(
            model_name='employee',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Хеш пароля'),
        ),
    ]
